config/routes.rb
FirstQuiz::Application.routes.draw do

  root 'ideas#index'
  resources :ideas
  get 'layout', to: 'ideas#layout'
  get 'about', to: 'ideas#about'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :idea, presence: true, length: {maximum: 50, minimum: 3 } 
  validates :whatisit, presence: true, length: {maximum: 300, minimum: 3 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @idea = Idea.order("RANDOM()").first
  end

  def create
    @idea = Idea.create(idea_params)
    if @idea.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
    end
    redirect_to root_path
  end

  def layout
    
  end

  def about
    
  end

  private

  def idea_params
    params.require(:idea).permit(:idea, :whatisit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About this site</h1>

    <p>This app was built by <a target="_blank" href="https://github.com/emmahoffman720">Emma</a> with beginning web developers in mind. Use this site to generate ideas for simple web pages for the student and hobbyist alike to create. You never run out of ideas, just sometimes struggle to think of one.  When you do come to a site like this to help find a solution.  And at the same time share with others the brilliant ideas you come up with in the spur of the moment.
    </p>
    <br />
    <p>If you would like to learn more about coding and web development <a target="_blank" href= "www.thefirehoseproject.com">click here.</a> 
    </p>

    <div class="col-xs-12 col-sm-4" style="padding-top:30px;">
    <%= image_tag 'profile-pic.jpg', class: 'img-responsive' %>
  </div>
  <div class="col-xs-12 col-sm-7 col-sm-offset-1">
    <h2 class="text-center">Emma Hoffman</h2>
    <br />
    <p>
      Emma Hoffman is a student currently enrolled in<a target="_blank" href="www.thefirehoseproject.com"> The Firehose Project</a> while also working as a barista.  This site was part of the curiculum at The Firehose Project to show what was taught in the beginning few chapters. It wraps up all the information cumutively and builds another web app of your choice to allow more practice.  
    </p>
  </div>

</div>

<br class="clear" />
<br />
<br />
<br />
<br />

app/views/ideas/index.html.erb
<h2> 
  <span>IDEA / No. <%= @idea.id %> </span>
  Here are the <u>best ideas</u> for a web site you can get!
</h2>

<h1><%= @idea.idea %></h1>
<h2>- <%= @idea.whatisit %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/ideas/layout.html.erb
<div class = "col-xs-10 col-xs-offset-1 layout">
  <h1> Layout examples </h1>

<br />
<br />
<br />

  <div class="col-xs-12 col-sm-7">
    <%= image_tag 'BlurredSplashPage.jpg', class: 'img-responsive' %>
  </div>

  <div class="col-xs-12 col-sm-4 col-sm-offset-1">
    <h2 class="text-center">Splash Page</h2>
    <br />
    <p>
      This is clear and simple page that does exactly what it is supposed to do.  Introduce you to the rest of the web.
    </p>

  </div>


  <br class="clear" />
  <br />
  <br />
  <br />
  <br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>FirstQuiz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class = "col-xs-4">
      <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
          <br />
            IDEAS
          <br />
            FOR THE
          <br />
            WEB
        </div>
      <% end %>
    </div>
    <div class = "col-xs-5 links">
      <!-- Button trigger modal -->
      <%= link_to 'Add Idea', '#', data: {toggle: 'modal', target: '#myModal'} %>
      &nbsp;
      <%= link_to 'Layouts', layout_path %>
      &nbsp;
      <%= link_to 'About', about_path %>
    </div>
    <div class = "col-xs-2 hidden-xs slogan">
      This site was created to help you create yours
    </div>
  </header>



  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add Your Idea</h4>
        </div>
        <%= simple_form_for Idea.new do |f| %>
          <div class="modal-body">
            <%= f.input :idea, label: "What is the idea you want to add?", placeholder: "Splash Web Page" %>
            <br />
            <%= f.input :whatisit, label: "Give a brief description of the site idea.", placeholder: "A simple page to introduce yourself to the internet." %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Add', class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <hr />

  <br class = "clear" />

  <div class = "container">

    <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>

  <%= yield %>

  </div>

  <div class="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-6">
        <%= link_to "Another idea", root_path, class: 'next-idea' %>
      </div>
      <div class="col-xs-12 col-sm-6 footer-blurb">
        Proudly hacked by <a href="https://github.com/emmahoffman720">Emma</a><br />
        Want to learn how to code <a href="http://thefirehoseproject.com">Click here</a>
      </div>
    </div>
  </div>

</body>
</html>